#!/usr/bin/env python3
"""Build the modular frontend bundle and optional standalone artifacts."""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path


HEADER = "/* Generated by scripts/build_standalone.py. Do not edit directly. */\n"


def module_files(root: Path) -> list[Path]:
    return sorted((root / "source" / "modules").glob("*.js"), key=lambda item: item.name)


def render_bundle(root: Path) -> str:
    files = module_files(root)
    if not files:
        raise ValueError("No JavaScript modules found in source/modules")
    sections = [HEADER]
    for file in files:
        source = file.read_text(encoding="utf-8").rstrip()
        sections.append(f"\n/* {file.name} */\n{source}\n")
    return "".join(sections)


def render_standalone(root: Path, bundle: str) -> str:
    source_dir = root / "source"
    html = (source_dir / "index.html").read_text(encoding="utf-8")
    css = (source_dir / "styles.css").read_text(encoding="utf-8").rstrip()
    safe_bundle = bundle.replace("</script", "<\\/script")
    html = re.sub(
        r'<link\s+rel=["\']stylesheet["\']\s+href=["\'](?:\./)?styles\.css["\']\s*/?>',
        f"<style>{css}</style>",
        html,
        count=1,
    )
    html = re.sub(
        r'<script\s+src=["\'](?:\./)?app\.js["\']\s*></script>',
        lambda _match: f"<script>{safe_bundle}</script>",
        html,
        count=1,
    )
    return html


def expected_outputs(root: Path, release: bool) -> dict[Path, str]:
    bundle = render_bundle(root)
    outputs = {root / "source" / "app.v3.js": bundle}
    if release:
        standalone = render_standalone(root, bundle)
        outputs.update(
            {
                root / "source" / "app.js": bundle,
                root / "source" / "yen-center-lms-demo.html": standalone,
                root / "OPEN-DEMO.html": standalone,
            }
        )
    return outputs


def check(outputs: dict[Path, str]) -> int:
    stale = [path for path, content in outputs.items() if not path.exists() or path.read_text(encoding="utf-8") != content]
    if stale:
        print("Generated artifacts are stale:")
        for path in stale:
            print(f"- {path}")
        return 1
    print(f"Generated artifacts are current ({len(outputs)} files).")
    return 0


def write(outputs: dict[Path, str]) -> int:
    for path, content in outputs.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")
        print(f"Wrote {path}")
    return 0


def parse_args(argv: list[str]) -> argparse.Namespace:
    parser = argparse.ArgumentParser()
    parser.add_argument("--root", type=Path, default=Path(__file__).resolve().parents[1])
    parser.add_argument("--check", action="store_true")
    parser.add_argument("--release", action="store_true")
    return parser.parse_args(argv)


def main(argv: list[str] | None = None) -> int:
    args = parse_args(argv or sys.argv[1:])
    outputs = expected_outputs(args.root.resolve(), args.release)
    return check(outputs) if args.check else write(outputs)


if __name__ == "__main__":
    raise SystemExit(main())
