#!/usr/bin/env python3
"""Build the modular frontend bundle and optional standalone artifacts."""

from __future__ import annotations

import argparse
import base64
import hashlib
import mimetypes
import re
import sys
from pathlib import Path


HEADER = "/* Generated by scripts/build_standalone.py. Do not edit directly. */\n"


def module_files(root: Path) -> list[Path]:
    return sorted((root / "source" / "modules").glob("*.js"), key=lambda item: item.name)


def render_bundle(root: Path) -> str:
    files = module_files(root)
    if not files:
        raise ValueError("No JavaScript modules found in source/modules")
    sections = [HEADER]
    for file in files:
        source = file.read_text(encoding="utf-8").rstrip()
        sections.append(f"\n/* {file.name} */\n{source}\n")
    return "".join(sections)


def inline_asset_urls(root: Path, html: str) -> str:
    """Embed local source/assets references so the release stays one portable file."""
    pattern = re.compile(r"(?P<quote>['\"])(?P<url>\./assets/[A-Za-z0-9_./-]+)(?P=quote)")

    def replace(match: re.Match[str]) -> str:
        relative = match.group("url").removeprefix("./")
        asset = root / "source" / relative
        if not asset.is_file():
            return match.group(0)
        mime = mimetypes.guess_type(asset.name)[0] or "application/octet-stream"
        encoded = base64.b64encode(asset.read_bytes()).decode("ascii")
        quote = match.group("quote")
        return f"{quote}data:{mime};base64,{encoded}{quote}"

    return pattern.sub(replace, html)


def render_standalone(root: Path, bundle: str) -> str:
    source_dir = root / "source"
    html = (source_dir / "index.html").read_text(encoding="utf-8")
    css = (source_dir / "styles.css").read_text(encoding="utf-8").rstrip()
    safe_bundle = bundle.replace("</script", "<\\/script")
    html = re.sub(
        r'<link\s+rel=["\']stylesheet["\']\s+href=["\'](?:\./)?styles\.css["\']\s*/?>',
        f"<style>{css}</style>",
        html,
        count=1,
    )
    html = re.sub(
        r'<script\s+src=["\'](?:\./)?app\.js["\']\s*></script>',
        lambda _match: f"<script>{safe_bundle}</script>",
        html,
        count=1,
    )
    return inline_asset_urls(root, html)


def expected_outputs(root: Path, release: bool) -> dict[Path, str]:
    bundle = render_bundle(root)
    outputs = {root / "source" / "app.v3.js": bundle}
    if release:
        standalone = render_standalone(root, bundle)
        outputs.update(
            {
                root / "source" / "app.js": bundle,
                root / "source" / "yen-center-lms-demo.html": standalone,
                root / "OPEN-DEMO.html": standalone,
            }
        )
    return outputs


def check(outputs: dict[Path, str]) -> int:
    stale = [path for path, content in outputs.items() if not path.exists() or path.read_text(encoding="utf-8") != content]
    if stale:
        print("Generated artifacts are stale:")
        for path in stale:
            print(f"- {path}")
        return 1
    print(f"Generated artifacts are current ({len(outputs)} files).")
    return 0


def write(outputs: dict[Path, str]) -> int:
    for path, content in outputs.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")
        print(f"Wrote {path}")
    return 0


def manifest_entries(root: Path) -> list[str]:
    manifest = root / "PACKAGE-MANIFEST.txt"
    if not manifest.exists():
        return []
    return [
        line.strip()
        for line in manifest.read_text(encoding="utf-8").splitlines()
        if re.fullmatch(r"[\w./-]+", line.strip()) and line.strip() != "CHECKSUMS-SHA256.txt"
    ]


def render_checksums(root: Path) -> str:
    lines = []
    for relative in manifest_entries(root):
        target = root / relative
        if not target.is_file():
            raise ValueError(f"Manifest file does not exist: {relative}")
        lines.append(f"{hashlib.sha256(target.read_bytes()).hexdigest()}  {relative}")
    return "\n".join(lines) + ("\n" if lines else "")


def write_checksums(root: Path) -> None:
    if not manifest_entries(root):
        return
    target = root / "CHECKSUMS-SHA256.txt"
    target.write_text(render_checksums(root), encoding="utf-8")
    print(f"Wrote {target}")


def check_checksums(root: Path) -> int:
    if not manifest_entries(root):
        return 0
    target = root / "CHECKSUMS-SHA256.txt"
    expected = render_checksums(root)
    if not target.exists() or target.read_text(encoding="utf-8") != expected:
        print(f"Generated artifact is stale: {target}")
        return 1
    print("Release checksums are current.")
    return 0


def parse_args(argv: list[str]) -> argparse.Namespace:
    parser = argparse.ArgumentParser()
    parser.add_argument("--root", type=Path, default=Path(__file__).resolve().parents[1])
    parser.add_argument("--check", action="store_true")
    parser.add_argument("--release", action="store_true")
    return parser.parse_args(argv)


def main(argv: list[str] | None = None) -> int:
    args = parse_args(argv or sys.argv[1:])
    root = args.root.resolve()
    outputs = expected_outputs(root, args.release)
    if args.check:
        result = check(outputs)
        return result or (check_checksums(root) if args.release else 0)
    result = write(outputs)
    if args.release and result == 0:
        write_checksums(root)
    return result


if __name__ == "__main__":
    raise SystemExit(main())
