/* Generated by scripts/build_standalone.py. Do not edit directly. */

/* 00-namespace.js */
(function initializeNamespace(root) {
  'use strict';

  const registry = Object.create(null);
  const YC = root.YC || {};

  YC.define = function define(name, value) {
    if (Object.prototype.hasOwnProperty.call(registry, name)) {
      throw new Error(`Service already defined: ${name}`);
    }
    registry[name] = value;
    YC[name] = value;
    return value;
  };

  YC.require = function requireService(name) {
    if (!Object.prototype.hasOwnProperty.call(registry, name)) {
      throw new Error(`Unknown service: ${name}`);
    }
    return registry[name];
  };

  root.YC = YC;
})(globalThis);

/* 01-utils.js */
(function defineUtilities(root) {
  'use strict';

  let sequence = 0;

  function escapeHtml(value) {
    return String(value ?? '')
      .replaceAll('&', '&amp;')
      .replaceAll('<', '&lt;')
      .replaceAll('>', '&gt;')
      .replaceAll('"', '&quot;')
      .replaceAll("'", '&#039;');
  }

  function uid(prefix = 'id') {
    sequence += 1;
    return `${prefix}-${Date.now().toString(36)}-${sequence.toString(36)}`;
  }

  function clone(value) {
    if (typeof structuredClone === 'function') return structuredClone(value);
    return JSON.parse(JSON.stringify(value));
  }

  function dateAt(clock, dayOffset = 0, hour = 9, minute = 0) {
    const date = new Date(clock());
    date.setHours(hour, minute, 0, 0);
    date.setDate(date.getDate() + dayOffset);
    return date.toISOString();
  }

  function formatDate(value, includeTime = false) {
    const options = includeTime
      ? { dateStyle: 'short', timeStyle: 'short' }
      : { day: '2-digit', month: '2-digit', year: 'numeric' };
    return new Intl.DateTimeFormat('vi-VN', options).format(new Date(value));
  }

  function percent(part, total) {
    return total ? Math.round((part / total) * 100) : 0;
  }

  root.YC.define('utils', Object.freeze({
    clone,
    dateAt,
    escapeHtml,
    formatDate,
    percent,
    uid,
  }));
})(globalThis);

/* 02-seed.js */
(function defineSeed(root) {
  'use strict';

  const { dateAt } = root.YC.utils;

  function createSeed(clock = () => new Date()) {
    const at = (days, hour = 9, minute = 0) => dateAt(clock, days, hour, minute);
    const learners = [
      { id: 'student-canonical', code: 'HS6A001', name: 'Nguyễn Minh Anh', birthDate: '2013-04-18', status: 'PROSPECT', classId: null, branchId: 'branch-q3', goal: 'Giao tiếp tự tin và củng cố nền tảng A2' },
      { id: 'student-02', code: 'HS6A002', name: 'Trần Gia Bảo', birthDate: '2013-07-09', status: 'ACTIVE', classId: 'class-6a', branchId: 'branch-q3', goal: 'Củng cố ngữ pháp' },
      { id: 'student-03', code: 'HS6A003', name: 'Lê Khánh Linh', birthDate: '2013-02-12', status: 'ACTIVE', classId: 'class-6a', branchId: 'branch-q3', goal: 'Phát triển kỹ năng nói' },
      { id: 'student-04', code: 'HS7B001', name: 'Phạm Đức Huy', birthDate: '2012-05-21', status: 'ACTIVE', classId: 'class-7b', branchId: 'branch-td', goal: 'Chuẩn bị B1' },
      { id: 'student-05', code: 'HS7B002', name: 'Vũ Ngọc Hà', birthDate: '2012-11-03', status: 'ACTIVE', classId: 'class-7b', branchId: 'branch-td', goal: 'Nâng kỹ năng viết' },
      { id: 'student-06', code: 'HS5C001', name: 'Đặng Minh Khang', birthDate: '2014-09-14', status: 'ACTIVE', classId: 'class-5c', branchId: 'branch-q3', goal: 'Xây nền A1' },
      { id: 'student-seat', code: 'HS6F001', name: 'Bùi Thanh An', birthDate: '2013-06-06', status: 'ACTIVE', classId: 'class-full', branchId: 'branch-q3', goal: 'Học cuối tuần' },
    ];

    const questions = [
      ['Yesterday, I ___ to school by bus.', ['go', 'went', 'gone', 'going'], 1],
      ['She ___ a new book last night.', ['reads', 'read', 'reading', 'has read'], 1],
      ['They ___ football on Sunday.', ['played', 'play', 'plays', 'playing'], 0],
      ['We ___ not at home yesterday.', ['was', 'were', 'are', 'be'], 1],
      ['___ you visit your grandmother last week?', ['Do', 'Did', 'Does', 'Were'], 1],
      ['Tom ___ breakfast at 7 a.m.', ['have', 'had', 'has', 'having'], 1],
      ['My parents ___ to Da Nang in June.', ['travel', 'traveled', 'travels', 'traveling'], 1],
      ['The movie ___ at nine o’clock.', ['end', 'ended', 'ends', 'ending'], 1],
      ['I ___ my homework before dinner.', ['finish', 'finished', 'finishes', 'finishing'], 1],
      ['Lan ___ happy after the test.', ['is', 'was', 'were', 'be'], 1],
    ].map((item, index) => ({
      id: `question-remedial-${index + 1}`,
      bankVersion: 1,
      type: 'SINGLE_CHOICE',
      prompt: item[0],
      options: item[1],
      correctIndex: item[2],
      competency: index < 6 ? 'LANGUAGE_USE' : 'READING',
      difficulty: index < 4 ? 'EASY' : index < 8 ? 'MEDIUM' : 'HARD',
    }));

    return {
      schemaVersion: 3,
      seededAt: new Date(clock()).toISOString(),
      migrationNotice: null,
      demo: { canonicalLearnerId: 'student-canonical', currentCheckpoint: 'RESET', mode: 'FRONTEND_ONLY' },
      settings: {
        organizationId: 'org-yen',
        correctionWindowHours: 24,
        remedialDeadlineDays: 7,
        minimumVideoProgress: 80,
        defaultPassingScore: 80,
        workloadLimitMinutes: 2400,
        integrationMode: 'MOCK',
      },
      organizations: [{ id: 'org-yen', name: 'Yen Center', status: 'ACTIVE' }],
      branches: [
        { id: 'branch-q3', organizationId: 'org-yen', code: 'Q3', name: 'Cơ sở Quận 3', address: '120 Võ Văn Tần, Quận 3', status: 'ACTIVE' },
        { id: 'branch-td', organizationId: 'org-yen', code: 'TD', name: 'Cơ sở Thủ Đức', address: '48 Võ Văn Ngân, Thủ Đức', status: 'ACTIVE' },
      ],
      users: [
        { id: 'admin-1', role: 'ADMIN', name: 'Nguyễn Minh Quân', identifiers: ['admin@yencenter.demo'], secret: 'Demo@123', status: 'ACTIVE', branchIds: ['branch-q3', 'branch-td'] },
        { id: 'manager-1', role: 'CENTER_MANAGER', name: 'Lê Thu Trang', identifiers: ['manager@yencenter.demo'], secret: 'Demo@123', status: 'ACTIVE', branchIds: ['branch-q3', 'branch-td'] },
        { id: 'admissions-1', role: 'ADMISSIONS', name: 'Trần Quỳnh Anh', identifiers: ['admissions@yencenter.demo'], secret: 'Demo@123', status: 'ACTIVE', branchIds: ['branch-q3'] },
        { id: 'academic-1', role: 'ACADEMIC_MANAGER', name: 'Phạm Hải Yến', identifiers: ['academic@yencenter.demo'], secret: 'Demo@123', status: 'ACTIVE', branchIds: ['branch-q3', 'branch-td'] },
        { id: 'service-1', role: 'STUDENT_SERVICE', name: 'Vũ Thanh Mai', identifiers: ['service@yencenter.demo'], secret: 'Demo@123', status: 'ACTIVE', branchIds: ['branch-q3', 'branch-td'] },
        { id: 'finance-1', role: 'FINANCE', name: 'Đỗ Minh Châu', identifiers: ['finance@yencenter.demo'], secret: 'Demo@123', status: 'ACTIVE', branchIds: ['branch-q3', 'branch-td'] },
        { id: 'teacher-1', role: 'TEACHER', name: 'Hoàng Yến', identifiers: ['teacher@yencenter.demo'], secret: 'Demo@123', status: 'ACTIVE', branchIds: ['branch-q3'] },
        { id: 'teacher-2', role: 'TEACHER', name: 'Lê Hải Nam', identifiers: ['nam@yencenter.demo'], secret: 'Demo@123', status: 'ACTIVE', branchIds: ['branch-td'] },
        { id: 'teacher-3', role: 'TEACHER', name: 'Phạm Thu Hương', identifiers: ['huong@yencenter.demo'], secret: 'Demo@123', status: 'ACTIVE', branchIds: ['branch-q3'] },
        { id: 'teacher-ineligible', role: 'TEACHER', name: 'David Trần', identifiers: ['david@yencenter.demo'], secret: 'Demo@123', status: 'ACTIVE', branchIds: ['branch-q3'] },
        { id: 'ta-1', role: 'TA', name: 'Trần Mai Anh', identifiers: ['ta@yencenter.demo'], secret: 'Demo@123', status: 'ACTIVE', branchIds: ['branch-q3'] },
        { id: 'student-login-1', role: 'STUDENT', name: 'Nguyễn Minh Anh', identifiers: ['HS6A001', '0901000001'], secret: '123456', status: 'ACTIVE', linkedLearnerIds: ['student-canonical'] },
        { id: 'parent-1', role: 'PARENT', name: 'Nguyễn Thu Hà', identifiers: ['0901000002'], secret: '123456', status: 'ACTIVE', linkedLearnerIds: ['student-canonical', 'student-03'] },
      ],
      roleScopes: [],
      learners,
      parentRelationships: [
        { id: 'relationship-1', parentUserId: 'parent-1', learnerId: 'student-canonical', type: 'MOTHER', status: 'VERIFIED' },
        { id: 'relationship-2', parentUserId: 'parent-1', learnerId: 'student-03', type: 'GUARDIAN', status: 'VERIFIED' },
      ],
      leads: [
        { id: 'lead-canonical', learnerId: 'student-canonical', code: 'YC-B2C-260901', type: 'B2C', name: 'Nguyễn Minh Anh', parentName: 'Nguyễn Thu Hà', phone: '0901000002', email: 'thuha@example.com', branchId: 'branch-q3', goal: 'Giao tiếp và nền tảng A2', availability: ['TUE_1800', 'THU_1800'], status: 'NEW', ownerId: 'admissions-1', createdAt: at(-2, 10) },
        { id: 'lead-no-seat', learnerId: null, code: 'YC-B2C-260902', type: 'B2C', name: 'Lâm Gia Huy', parentName: 'Lâm Ngọc Lan', phone: '0902000001', email: '', branchId: 'branch-q3', goal: 'Lớp cuối tuần', availability: ['SAT_0900'], status: 'PLACED', ownerId: 'admissions-1', createdAt: at(-4, 9) },
        { id: 'lead-b2b', learnerId: null, code: 'YC-B2B-260801', type: 'B2B', name: 'Ngô Quốc Việt', organization: 'Trường Ánh Dương', phone: '0903000001', email: 'viet@anhduong.demo', branchId: 'branch-td', goal: 'Demo cho 300 học viên', availability: [], status: 'CONTACTED', ownerId: 'admissions-1', createdAt: at(-7, 14) },
      ],
      consultations: [],
      placementBookings: [],
      placementResults: [
        { id: 'placement-no-seat', leadId: 'lead-no-seat', learnerId: null, status: 'RELEASED', frameworkLevel: 'A2', centerLevelId: 'level-a2-1', skills: { listening: 72, reading: 75, spokenInteraction: 68, spokenProduction: 66, writing: 70, language: 71 }, recommendation: 'English Foundation 6 · A2.1', reviewedBy: 'academic-1', releasedAt: at(-3, 15) },
      ],
      programs: [
        { id: 'program-foundation', name: 'English Foundation', audience: 'Young Learners', outcome: 'Nền tảng giao tiếp và học thuật theo CEFR', status: 'PUBLISHED' },
        { id: 'program-ielts', name: 'IELTS Pathway', audience: 'Teen & Adult', outcome: 'Lộ trình học thuật và luyện thi', status: 'PUBLISHED' },
        { id: 'program-speaking', name: 'Speaking Clinic', audience: 'All Learners', outcome: 'Tăng tương tác và phát âm', status: 'PUBLISHED' },
      ],
      levels: [
        { id: 'level-a1', programId: 'program-foundation', code: 'A1', name: 'Foundation A1', sequence: 1 },
        { id: 'level-a2-1', programId: 'program-foundation', code: 'A2.1', name: 'Foundation A2.1', sequence: 2 },
        { id: 'level-a2-2', programId: 'program-foundation', code: 'A2.2', name: 'Foundation A2.2', sequence: 3 },
      ],
      courses: [
        { id: 'course-6', programId: 'program-foundation', levelId: 'level-a2-1', code: 'ENG-FND-6', name: 'English Foundation 6', status: 'PUBLISHED' },
        { id: 'course-7', programId: 'program-foundation', levelId: 'level-a2-2', code: 'ENG-FND-7', name: 'English Foundation 7', status: 'PUBLISHED' },
        { id: 'course-5', programId: 'program-foundation', levelId: 'level-a1', code: 'ENG-FND-5', name: 'English Foundation 5', status: 'PUBLISHED' },
      ],
      courseVersions: [
        { id: 'course-v6', courseId: 'course-6', version: 3, title: 'English Foundation 6 · A2.1', status: 'PUBLISHED', immutable: true, totalHours: 48, completionRule: { attendanceMinimum: 75, finalScoreMinimum: 70, skillMinimum: 60 }, publishedAt: at(-90) },
        { id: 'course-v7', courseId: 'course-7', version: 2, title: 'English Foundation 7 · A2.2', status: 'PUBLISHED', immutable: true, totalHours: 48, completionRule: { attendanceMinimum: 75, finalScoreMinimum: 72, skillMinimum: 62 }, publishedAt: at(-80) },
        { id: 'course-v5', courseId: 'course-5', version: 4, title: 'English Foundation 5 · A1', status: 'PUBLISHED', immutable: true, totalHours: 42, completionRule: { attendanceMinimum: 70, finalScoreMinimum: 65, skillMinimum: 55 }, publishedAt: at(-75) },
      ],
      units: [
        { id: 'unit-v6-4', courseVersionId: 'course-v6', order: 4, title: 'Past experiences', outcome: 'Kể lại trải nghiệm đã xảy ra' },
        { id: 'unit-v7-3', courseVersionId: 'course-v7', order: 3, title: 'Future choices', outcome: 'Thảo luận kế hoạch và lựa chọn' },
        { id: 'unit-v5-2', courseVersionId: 'course-v5', order: 2, title: 'Daily routines', outcome: 'Mô tả thói quen hằng ngày' },
      ],
      lessonTemplates: [
        { id: 'lesson-past-simple', unitId: 'unit-v6-4', version: 2, title: 'Unit 4 · Lesson 2: Past Simple', durationMinutes: 90, objectives: ['Dùng past simple chính xác', 'Kể lại một trải nghiệm ngắn'], status: 'PUBLISHED' },
        { id: 'lesson-future', unitId: 'unit-v7-3', version: 1, title: 'Unit 3 · Lesson 1: Future choices', durationMinutes: 90, objectives: ['So sánh lựa chọn tương lai'], status: 'PUBLISHED' },
        { id: 'lesson-routines', unitId: 'unit-v5-2', version: 1, title: 'Unit 2 · Lesson 1: Daily routines', durationMinutes: 90, objectives: ['Mô tả lịch sinh hoạt'], status: 'PUBLISHED' },
      ],
      learningItems: [
        { id: 'item-past-simple-video', lessonTemplateId: 'lesson-past-simple', type: 'VIDEO', title: 'Past Simple in context', required: true, durationMinutes: 18, order: 1 },
        { id: 'item-speaking-pairs', lessonTemplateId: 'lesson-past-simple', type: 'LIVE_ACTIVITY', title: 'Pair storytelling', required: true, durationMinutes: 22, order: 2 },
        { id: 'item-pronunciation', lessonTemplateId: 'lesson-past-simple', type: 'PRACTICE', title: 'Pronunciation: -ed endings', required: true, durationMinutes: 15, order: 3 },
        { id: 'item-remedial-quiz', lessonTemplateId: 'lesson-past-simple', type: 'QUIZ', title: 'Past Simple Check', required: true, durationMinutes: 15, order: 4 },
      ],
      teacherProfiles: [
        { id: 'teacher-profile-1', userId: 'teacher-1', teacherCode: 'GV001', status: 'ACTIVE', branchIds: ['branch-q3'], ageBands: ['YOUNG_LEARNER', 'TEEN'], levels: ['A1', 'A2', 'B1'], modes: ['OFFLINE', 'ONLINE'] },
        { id: 'teacher-profile-2', userId: 'teacher-2', teacherCode: 'GV002', status: 'ACTIVE', branchIds: ['branch-td'], ageBands: ['TEEN', 'ADULT'], levels: ['A2', 'B1', 'B2'], modes: ['OFFLINE', 'ONLINE'] },
        { id: 'teacher-profile-3', userId: 'teacher-3', teacherCode: 'GV003', status: 'ACTIVE', branchIds: ['branch-q3'], ageBands: ['YOUNG_LEARNER', 'TEEN'], levels: ['A1', 'A2', 'B1'], modes: ['OFFLINE', 'HYBRID'] },
        { id: 'teacher-profile-ineligible', userId: 'teacher-ineligible', teacherCode: 'GV004', status: 'ACTIVE', branchIds: ['branch-q3'], ageBands: ['ADULT'], levels: ['B2', 'C1'], modes: ['ONLINE'] },
      ],
      qualifications: [
        { id: 'qualification-1', teacherProfileId: 'teacher-profile-1', type: 'TESOL', level: 'ALL', issuedAt: at(-500), expiresAt: at(300), status: 'VALID' },
        { id: 'qualification-2', teacherProfileId: 'teacher-profile-2', type: 'CELTA', level: 'ALL', issuedAt: at(-800), expiresAt: at(180), status: 'VALID' },
        { id: 'qualification-4', teacherProfileId: 'teacher-profile-3', type: 'TESOL', level: 'ALL', issuedAt: at(-450), expiresAt: at(240), status: 'VALID' },
        { id: 'qualification-3', teacherProfileId: 'teacher-profile-ineligible', type: 'BUSINESS_ENGLISH', level: 'ADULT', issuedAt: at(-300), expiresAt: at(120), status: 'VALID' },
      ],
      availabilitySlots: [
        { id: 'availability-1', teacherProfileId: 'teacher-profile-1', day: 'TUE', start: '17:30', end: '21:00', branchId: 'branch-q3', mode: 'OFFLINE', effectiveFrom: at(-30), effectiveTo: at(120) },
        { id: 'availability-2', teacherProfileId: 'teacher-profile-1', day: 'THU', start: '17:30', end: '21:00', branchId: 'branch-q3', mode: 'OFFLINE', effectiveFrom: at(-30), effectiveTo: at(120) },
        { id: 'availability-3', teacherProfileId: 'teacher-profile-2', day: 'MON', start: '18:00', end: '21:00', branchId: 'branch-td', mode: 'OFFLINE', effectiveFrom: at(-30), effectiveTo: at(120) },
        { id: 'availability-4', teacherProfileId: 'teacher-profile-3', day: 'TUE', start: '17:00', end: '21:00', branchId: 'branch-q3', mode: 'OFFLINE', effectiveFrom: at(-30), effectiveTo: at(120) },
      ],
      teacherAssignments: [
        { id: 'teacher-assignment-7b', teacherProfileId: 'teacher-profile-2', classId: 'class-7b', role: 'PRIMARY', startsAt: at(-30), endsAt: at(120), workloadMinutes: 720, status: 'ACTIVE', acceptedAt: at(-35), assignedBy: 'academic-1' },
      ],
      sessionAssignments: [],
      classes: [
        { id: 'class-6a', code: 'ENG6A-T3T5-1800', name: 'English Foundation 6A', branchId: 'branch-q3', courseVersionId: 'course-v6', ageBand: 'YOUNG_LEARNER', mode: 'OFFLINE', capacity: 14, room: 'P.302', scheduleLabel: 'Thứ 3 & 5 · 18:00', status: 'OPEN' },
        { id: 'class-6b', code: 'ENG6B-T2T4-1830', name: 'English Foundation 6B', branchId: 'branch-q3', courseVersionId: 'course-v6', ageBand: 'YOUNG_LEARNER', mode: 'HYBRID', capacity: 12, room: 'P.204', scheduleLabel: 'Thứ 2 & 4 · 18:30', status: 'OPEN' },
        { id: 'class-7b', code: 'ENG7B-T2T4-1900', name: 'English Foundation 7B', branchId: 'branch-td', courseVersionId: 'course-v7', ageBand: 'TEEN', mode: 'OFFLINE', capacity: 12, room: 'P.105', scheduleLabel: 'Thứ 2 & 4 · 19:00', status: 'ACTIVE' },
        { id: 'class-5c', code: 'ENG5C-T7CN-0900', name: 'English Foundation 5C', branchId: 'branch-q3', courseVersionId: 'course-v5', ageBand: 'YOUNG_LEARNER', mode: 'OFFLINE', capacity: 10, room: 'P.101', scheduleLabel: 'Thứ 7 & CN · 09:00', status: 'ACTIVE' },
        { id: 'class-full', code: 'ENG6F-T7-0900', name: 'English Foundation 6 Cuối tuần', branchId: 'branch-q3', courseVersionId: 'course-v6', ageBand: 'YOUNG_LEARNER', mode: 'OFFLINE', capacity: 1, room: 'P.305', scheduleLabel: 'Thứ 7 · 09:00', status: 'FULL' },
      ],
      enrollments: learners.filter((item) => item.classId).map((learner, index) => ({ id: `enrollment-seed-${index + 1}`, learnerId: learner.id, classId: learner.classId, courseVersionId: learner.classId === 'class-7b' ? 'course-v7' : learner.classId === 'class-5c' ? 'course-v5' : 'course-v6', status: 'ACTIVE', startsAt: at(-25), endsAt: null })),
      timetableRules: [
        { id: 'timetable-6a', classId: 'class-6a', recurrence: ['TUE_1800', 'THU_1800'], durationMinutes: 90, room: 'P.302', branchId: 'branch-q3' },
        { id: 'timetable-7b', classId: 'class-7b', recurrence: ['MON_1900', 'WED_1900'], durationMinutes: 90, room: 'P.105', branchId: 'branch-td' },
      ],
      sessions: [
        { id: 'session-canonical', classId: 'class-6a', lessonTemplateId: 'lesson-past-simple', startsAt: at(0, 18), endsAt: at(0, 19, 30), room: 'P.302', mode: 'OFFLINE', status: 'CONFIRMED', attendanceFinalized: false },
        { id: 'session-7b', classId: 'class-7b', lessonTemplateId: 'lesson-future', startsAt: at(1, 19), endsAt: at(1, 20, 30), room: 'P.105', mode: 'OFFLINE', status: 'CONFIRMED', attendanceFinalized: false },
      ],
      attendanceRecords: [],
      lessonPlans: [{ id: 'lesson-plan-canonical', sessionId: 'session-canonical', lessonTemplateId: 'lesson-past-simple', adaptations: ['Thêm visual timeline cho past simple'], readiness: 'DRAFT', ownerId: 'teacher-1' }],
      deliveryRecords: [],
      homeworkAssignments: [],
      homeworkSubmissions: [],
      assessments: [
        { id: 'assessment-remedial', lessonTemplateId: 'lesson-past-simple', purpose: 'FORMATIVE', title: 'Past Simple Check', questionIds: questions.map((item) => item.id), passingScore: 80, maxAttempts: 3, gradingMode: 'AUTO', status: 'PUBLISHED' },
        { id: 'assessment-final-canonical', courseVersionId: 'course-v6', purpose: 'FINAL', title: 'A2.1 Final Portfolio', questionIds: [], passingScore: 70, maxAttempts: 1, gradingMode: 'MANUAL', status: 'PUBLISHED' },
      ],
      questions,
      attempts: [],
      gradingRecords: [],
      moderationCases: [],
      skillResults: [],
      packages: [{ id: 'package-a2-1', courseVersionId: 'course-v6', name: 'English Foundation A2.1 · Trọn khóa', price: 6800000, currency: 'VND', validityDays: 120, status: 'ACTIVE' }],
      offers: [],
      invoices: [],
      payments: [],
      refunds: [],
      renewals: [],
      remedialAssignments: [],
      videoProgressRecords: [],
      progressReports: [],
      promotionDecisions: [],
      interventionCases: [
        { id: 'intervention-seed', learnerId: 'student-03', signal: 'HOMEWORK_BELOW_50', ownerRole: 'TEACHER', ownerId: 'teacher-1', status: 'OPEN', plan: 'Speaking clinic và lịch practice 2 buổi/tuần', followUpAt: at(5), outcome: null },
      ],
      serviceCases: [
        { id: 'service-no-seat', learnerId: null, leadId: 'lead-no-seat', type: 'NO_SEAT', ownerId: 'service-1', status: 'OPEN', reason: 'Lớp cuối tuần đã đủ chỗ', createdAt: at(-2) },
      ],
      makeUpBookings: [],
      substitutions: [
        { id: 'substitution-seed', sessionId: 'session-7b', originalTeacherProfileId: 'teacher-profile-2', replacementTeacherProfileId: null, reason: 'Giáo viên chính bận công tác', status: 'REQUESTED', handover: null, accessStartsAt: null, accessEndsAt: null },
      ],
      feedbackRecords: [
        { id: 'feedback-parent', learnerId: 'student-03', authorId: 'teacher-1', type: 'ACADEMIC', visibility: 'LEARNER_PARENT', body: 'Linh có tiến bộ tốt ở phần tương tác nói.', createdAt: at(-1) },
        { id: 'feedback-internal', learnerId: 'student-03', authorId: 'academic-1', type: 'COACHING', visibility: 'ACADEMIC_ONLY', body: 'Cần quan sát thêm cách phân nhóm hoạt động.', createdAt: at(-1) },
        { id: 'feedback-safeguarding', learnerId: 'student-canonical', authorId: 'teacher-1', type: 'SAFEGUARDING', visibility: 'RESTRICTED', body: 'Restricted demonstration record.', createdAt: at(-1) },
      ],
      notifications: [],
      outboundMessages: [],
      domainEvents: [],
      auditLogs: [{ id: 'audit-seed', actorId: 'admin-1', action: 'DEMO_DATA_SEEDED', resourceType: 'SYSTEM', resourceId: 'org-yen', detail: 'Khởi tạo dữ liệu demo v3.', occurredAt: at(0, 8) }],
      analyticsSnapshots: [],
      publicContent: {
        news: [{ id: 'news-1', title: 'Khai giảng lộ trình tiếng Anh tháng 9', category: 'Thông báo', publishedAt: at(-2), status: 'PUBLISHED' }],
        events: [{ id: 'event-1', title: 'Kiểm tra đầu vào miễn phí', startsAt: at(4, 9), location: 'Cơ sở Quận 3', status: 'PUBLISHED' }],
        documents: [{ id: 'document-1', title: 'Hướng dẫn cổng học tập', audience: 'Phụ huynh & Học viên', type: 'PDF', status: 'PUBLISHED' }],
      },
    };
  }

  root.YC.define('seed', Object.freeze({ createSeed }));
})(globalThis);

/* 03-store.js */
(function defineStore(root) {
  'use strict';

  const { clone } = root.YC.utils;
  const STORAGE_KEY = 'yen-center-lms-fe-state-v3';
  const LEGACY_STORAGE_KEY = 'yen-center-lms-fe-state-v2';
  const SESSION_KEY = 'yen-center-lms-fe-session-v3';

  function browserStorage() {
    try {
      return root.localStorage;
    } catch (_error) {
      return null;
    }
  }

  function create({ storage = browserStorage(), clock = () => new Date() } = {}) {
    let current;

    function persist() {
      if (storage) storage.setItem(STORAGE_KEY, JSON.stringify(current));
    }

    function fresh(migrationNotice = null) {
      const seeded = root.YC.seed.createSeed(clock);
      seeded.migrationNotice = migrationNotice;
      return seeded;
    }

    function load() {
      if (storage) {
        try {
          const raw = storage.getItem(STORAGE_KEY);
          if (raw) {
            const parsed = JSON.parse(raw);
            if (parsed.schemaVersion === 3) return parsed;
          }
          if (storage.getItem(LEGACY_STORAGE_KEY)) {
            return fresh({ code: 'V2_RESET_REQUIRED', message: 'Dữ liệu v2 đã được thay bằng seed v3 để bảo toàn quan hệ nghiệp vụ.' });
          }
        } catch (_error) {
          return fresh({ code: 'CORRUPT_STATE_RESET', message: 'Dữ liệu local không hợp lệ đã được reset an toàn.' });
        }
      }
      return fresh();
    }

    current = load();
    persist();

    return Object.freeze({
      getState() { return current; },
      replace(next) {
        if (!next || next.schemaVersion !== 3) throw new Error('StateV3 required');
        current = clone(next);
        persist();
        return current;
      },
      reset() {
        current = fresh();
        persist();
        return current;
      },
      transact(mutator) {
        const draft = clone(current);
        const result = mutator(draft);
        current = draft;
        persist();
        return result;
      },
      storage,
      clock,
    });
  }

  root.YC.define('store', Object.freeze({ create, LEGACY_STORAGE_KEY, SESSION_KEY, STORAGE_KEY }));
})(globalThis);

/* 04-policy.js */
(function definePolicy(root) {
  'use strict';

  const roleCapabilities = Object.freeze({
    ADMIN: ['*'],
    CENTER_MANAGER: ['DASHBOARD_VIEW', 'CLASS_VIEW', 'REPORT_VIEW', 'QUALITY_VIEW'],
    ADMISSIONS: ['LEAD_VIEW', 'LEAD_EDIT', 'PLACEMENT_VIEW', 'OFFER_EDIT', 'RENEWAL_EDIT'],
    ACADEMIC_MANAGER: ['CLASS_VIEW', 'CURRICULUM_EDIT', 'TEACHER_ASSIGN', 'GRADE_REVIEW', 'PROGRESS_APPROVE', 'QUALITY_VIEW'],
    STUDENT_SERVICE: ['CLASS_VIEW', 'ALLOCATION_EDIT', 'SERVICE_CASE_EDIT', 'ATTENDANCE_CORRECT', 'SUBSTITUTION_EDIT'],
    FINANCE: ['INVOICE_EDIT', 'PAYMENT_EDIT', 'REFUND_EDIT', 'TUITION_VIEW'],
    TEACHER: ['CLASS_VIEW', 'SESSION_DELIVER', 'ATTENDANCE_EDIT', 'HOMEWORK_EDIT', 'GRADE_EDIT', 'LEARNER_VIEW'],
    TA: ['CLASS_VIEW', 'ATTENDANCE_EDIT', 'LEARNER_VIEW'],
    STUDENT: ['OWN_LEARNING_VIEW', 'OWN_LEARNING_EDIT'],
    PARENT: ['LINKED_LEARNER_VIEW', 'TUITION_VIEW'],
  });

  function assignmentAllows(actor, resource, state) {
    const profile = state.teacherProfiles.find((item) => item.userId === actor.id);
    if (!profile || !resource.classId) return false;
    const moment = new Date(state.seededAt).getTime();
    return state.teacherAssignments.some((item) => item.teacherProfileId === profile.id
      && item.classId === resource.classId
      && ['ACCEPTED', 'ACTIVE'].includes(item.status)
      && new Date(item.startsAt).getTime() <= moment
      && new Date(item.endsAt).getTime() >= moment);
  }

  function can(actor, capability, resource = {}, state) {
    if (!actor || actor.status !== 'ACTIVE') return false;
    const allowed = roleCapabilities[actor.role] || [];
    if (!allowed.includes('*') && !allowed.includes(capability)) return false;
    if (actor.role === 'ADMIN') return true;
    if (resource.branchId && actor.branchIds && !actor.branchIds.includes(resource.branchId)) return false;
    if (['TEACHER', 'TA'].includes(actor.role) && ['CLASS_VIEW', 'LEARNER_VIEW', 'SESSION_DELIVER', 'ATTENDANCE_EDIT', 'HOMEWORK_EDIT', 'GRADE_EDIT'].includes(capability)) {
      return assignmentAllows(actor, resource, state);
    }
    if (actor.role === 'STUDENT' && resource.learnerId) return (actor.linkedLearnerIds || []).includes(resource.learnerId);
    if (actor.role === 'PARENT' && resource.learnerId) return (actor.linkedLearnerIds || []).includes(resource.learnerId);
    return true;
  }

  function visibleFeedback(actor, records, state) {
    if (!actor) return [];
    if (['ADMIN', 'ACADEMIC_MANAGER'].includes(actor.role)) return records.slice();
    if (actor.role === 'PARENT') {
      return records.filter((item) => (actor.linkedLearnerIds || []).includes(item.learnerId)
        && ['PARENT', 'LEARNER_PARENT'].includes(item.visibility));
    }
    if (actor.role === 'STUDENT') {
      return records.filter((item) => (actor.linkedLearnerIds || []).includes(item.learnerId)
        && ['LEARNER', 'LEARNER_PARENT'].includes(item.visibility));
    }
    if (actor.role === 'TEACHER') {
      return records.filter((item) => item.visibility !== 'RESTRICTED'
        && can(actor, 'LEARNER_VIEW', { learnerId: item.learnerId, classId: state.learners.find((learner) => learner.id === item.learnerId)?.classId }, state));
    }
    return [];
  }

  root.YC.define('policy', Object.freeze({ can, roleCapabilities, visibleFeedback }));
})(globalThis);

/* 05-commands.js */
(function defineCommands(root) {
  'use strict';

  const { uid } = root.YC.utils;

  class CommandError extends Error {
    constructor(code, message, details = {}) {
      super(message);
      this.name = 'CommandError';
      this.code = code;
      Object.assign(this, details);
    }
  }

  function required(value, code, message) {
    if (!value) throw new CommandError(code, message);
    return value;
  }

  function requireRole(actor, roles) {
    required(actor, 'AUTH_REQUIRED', 'Cần đăng nhập để thực hiện thao tác này.');
    if (!roles.includes(actor.role) && actor.role !== 'ADMIN') {
      throw new CommandError('FORBIDDEN', 'Vai trò hiện tại không có quyền thực hiện thao tác này.');
    }
  }

  function create(store) {
    function nowIso() {
      return new Date(store.clock()).toISOString();
    }

    function appendEvent(draft, context, type, resourceType, resourceId, summary, extra = {}) {
      const event = {
        id: uid('event'),
        type,
        resourceType,
        resourceId,
        actorId: context.actor.id,
        occurredAt: nowIso(),
        summary,
        ...extra,
      };
      draft.domainEvents.unshift(event);
      context.eventIds.push(event.id);
      return event;
    }

    function appendAudit(draft, context, action, resourceType, resourceId, detail) {
      draft.auditLogs.unshift({
        id: uid('audit'),
        actorId: context.actor.id,
        action,
        resourceType,
        resourceId,
        detail,
        occurredAt: nowIso(),
      });
    }

    function notifyRole(draft, role, title, body, link = '') {
      const recipient = draft.users.find((item) => item.role === role && item.status === 'ACTIVE');
      if (!recipient) return;
      draft.notifications.unshift({ id: uid('notification'), userId: recipient.id, title, body, link, read: false, createdAt: nowIso() });
    }

    function findLead(draft, leadId) {
      return required(draft.leads.find((item) => item.id === leadId), 'LEAD_NOT_FOUND', 'Không tìm thấy lead.');
    }

    function latestForLead(collection, leadId) {
      return collection.filter((item) => item.leadId === leadId).at(-1) || null;
    }

    const handlers = {
      CONTACT_LEAD(draft, payload, context) {
        requireRole(context.actor, ['ADMISSIONS']);
        const lead = findLead(draft, payload.leadId);
        if (lead.status !== 'NEW') throw new CommandError('INVALID_LEAD_STATE', 'Lead chỉ được liên hệ lần đầu từ trạng thái NEW.');
        lead.status = 'CONTACTED';
        lead.contactedAt = nowIso();
        draft.consultations.push({ id: uid('consultation'), leadId: lead.id, ownerId: context.actor.id, note: payload.note || 'Đã xác nhận nhu cầu.', occurredAt: nowIso() });
        appendEvent(draft, context, 'LEAD_CONTACTED', 'LEAD', lead.id, `${lead.name} đã được liên hệ.` , { learnerId: lead.learnerId });
        appendAudit(draft, context, 'LEAD_CONTACTED', 'LEAD', lead.id, payload.note || 'Xác nhận nhu cầu học.');
        return { message: 'Đã liên hệ và ghi nhận nhu cầu.' };
      },

      BOOK_PLACEMENT(draft, payload, context) {
        requireRole(context.actor, ['ADMISSIONS']);
        const lead = findLead(draft, payload.leadId);
        if (lead.status !== 'CONTACTED') throw new CommandError('LEAD_NOT_CONTACTED', 'Cần liên hệ lead trước khi đặt placement.');
        lead.status = 'PLACEMENT_BOOKED';
        const booking = { id: uid('placement-booking'), leadId: lead.id, learnerId: lead.learnerId, branchId: lead.branchId, startsAt: payload.startsAt, mode: payload.mode || 'OFFLINE', status: 'BOOKED', createdBy: context.actor.id };
        draft.placementBookings.push(booking);
        appendEvent(draft, context, 'PLACEMENT_BOOKED', 'PLACEMENT_BOOKING', booking.id, `Đặt lịch placement cho ${lead.name}.`, { learnerId: lead.learnerId });
        appendAudit(draft, context, 'PLACEMENT_BOOKED', 'PLACEMENT_BOOKING', booking.id, `${payload.startsAt} · ${booking.mode}`);
        notifyRole(draft, 'ACADEMIC_MANAGER', 'Có lịch placement mới', `${lead.name} cần được đánh giá đầu vào.`, '/app/academic/dashboard');
        return { message: 'Đã đặt lịch placement.' };
      },

      RECORD_PLACEMENT(draft, payload, context) {
        requireRole(context.actor, ['ACADEMIC_MANAGER']);
        const lead = findLead(draft, payload.leadId);
        const booking = latestForLead(draft.placementBookings, lead.id);
        if (!booking || booking.status !== 'BOOKED') throw new CommandError('PLACEMENT_NOT_BOOKED', 'Cần có booking placement hợp lệ trước khi ghi kết quả.');
        if (draft.placementResults.some((item) => item.leadId === lead.id)) throw new CommandError('PLACEMENT_EXISTS', 'Lead đã có kết quả placement.');
        booking.status = 'COMPLETED';
        const result = {
          id: uid('placement'),
          leadId: lead.id,
          learnerId: lead.learnerId,
          status: 'REVIEWED',
          frameworkLevel: payload.frameworkLevel,
          centerLevelId: payload.centerLevelId,
          skills: { ...payload.skills },
          recommendation: payload.recommendation,
          reviewedBy: context.actor.id,
          recordedAt: nowIso(),
        };
        draft.placementResults.push(result);
        appendEvent(draft, context, 'PLACEMENT_RECORDED', 'PLACEMENT_RESULT', result.id, `${lead.name}: ${result.frameworkLevel} · ${result.recommendation}.`, { learnerId: lead.learnerId });
        appendAudit(draft, context, 'PLACEMENT_RECORDED', 'PLACEMENT_RESULT', result.id, 'Kết quả đa kỹ năng đã được ghi nhận.');
        return { message: 'Đã ghi kết quả placement.' };
      },

      RELEASE_PLACEMENT(draft, payload, context) {
        requireRole(context.actor, ['ACADEMIC_MANAGER']);
        const lead = findLead(draft, payload.leadId);
        const result = latestForLead(draft.placementResults, lead.id);
        if (!result || result.status !== 'REVIEWED') throw new CommandError('PLACEMENT_NOT_REVIEWED', 'Kết quả placement chưa sẵn sàng để release.');
        result.status = 'RELEASED';
        result.releasedAt = nowIso();
        lead.status = 'PLACED';
        appendEvent(draft, context, 'PLACEMENT_RELEASED', 'PLACEMENT_RESULT', result.id, `Đã phát hành khuyến nghị ${result.recommendation}.`, { learnerId: lead.learnerId });
        appendAudit(draft, context, 'PLACEMENT_RELEASED', 'PLACEMENT_RESULT', result.id, 'Academic Manager phê duyệt kết quả.');
        notifyRole(draft, 'ADMISSIONS', 'Placement đã được phát hành', `${lead.name}: ${result.recommendation}.`, '/app/admissions/offers');
        return { message: 'Đã phát hành kết quả placement.' };
      },

      CREATE_OFFER(draft, payload, context) {
        requireRole(context.actor, ['ADMISSIONS']);
        const lead = findLead(draft, payload.leadId);
        const placement = latestForLead(draft.placementResults, lead.id);
        if (!placement || placement.status !== 'RELEASED') throw new CommandError('PLACEMENT_NOT_RELEASED', 'Cần placement đã phát hành trước khi tạo offer.');
        const packageItem = required(draft.packages.find((item) => item.id === payload.packageId), 'PACKAGE_NOT_FOUND', 'Không tìm thấy package.');
        const discount = Math.max(0, Number(payload.discount || 0));
        const offer = { id: uid('offer'), leadId: lead.id, learnerId: lead.learnerId, packageId: packageItem.id, listPrice: packageItem.price, discount, total: packageItem.price - discount, currency: packageItem.currency, status: 'DRAFT', createdBy: context.actor.id, createdAt: nowIso() };
        draft.offers.push(offer);
        lead.status = 'OFFERED';
        appendEvent(draft, context, 'OFFER_CREATED', 'OFFER', offer.id, `Offer ${offer.total.toLocaleString('vi-VN')} ${offer.currency}.`, { learnerId: lead.learnerId });
        appendAudit(draft, context, 'OFFER_CREATED', 'OFFER', offer.id, `Giảm ${discount.toLocaleString('vi-VN')} ${offer.currency}.`);
        return { message: 'Đã tạo offer nháp.' };
      },

      SEND_OFFER(draft, payload, context) {
        requireRole(context.actor, ['ADMISSIONS']);
        const lead = findLead(draft, payload.leadId);
        const offer = required(latestForLead(draft.offers, lead.id), 'OFFER_NOT_FOUND', 'Không tìm thấy offer.');
        if (offer.status !== 'DRAFT') throw new CommandError('INVALID_OFFER_STATE', 'Chỉ offer nháp mới được gửi.');
        offer.status = 'SENT';
        offer.sentAt = nowIso();
        draft.outboundMessages.unshift({ id: uid('outbound'), channel: 'EMAIL', recipient: lead.email || lead.phone, template: 'OFFER_SENT', status: 'MOCKED', mode: 'MOCK', createdAt: nowIso() });
        appendEvent(draft, context, 'OFFER_SENT', 'OFFER', offer.id, `Đã gửi offer mock cho ${lead.parentName || lead.name}.`, { learnerId: lead.learnerId });
        appendAudit(draft, context, 'OFFER_SENT_MOCK', 'OFFER', offer.id, 'Outbound mock, không gửi ra provider thật.');
        return { message: 'Đã gửi offer ở chế độ mock.' };
      },

      ACCEPT_OFFER(draft, payload, context) {
        requireRole(context.actor, ['ADMISSIONS']);
        const lead = findLead(draft, payload.leadId);
        const offer = required(latestForLead(draft.offers, lead.id), 'OFFER_NOT_FOUND', 'Không tìm thấy offer.');
        if (offer.status !== 'SENT') throw new CommandError('OFFER_NOT_SENT', 'Offer phải được gửi trước khi ghi nhận chấp nhận.');
        offer.status = 'ACCEPTED';
        offer.acceptedAt = nowIso();
        appendEvent(draft, context, 'OFFER_ACCEPTED', 'OFFER', offer.id, `${lead.parentName || lead.name} đã chấp nhận offer.`, { learnerId: lead.learnerId });
        appendAudit(draft, context, 'OFFER_ACCEPTED', 'OFFER', offer.id, 'Admissions ghi nhận xác nhận trong demo.');
        notifyRole(draft, 'FINANCE', 'Offer chờ xuất hóa đơn', `${lead.name} đã chấp nhận offer.`, '/app/finance/invoices');
        return { message: 'Đã ghi nhận offer được chấp nhận.' };
      },

      ISSUE_INVOICE(draft, payload, context) {
        requireRole(context.actor, ['FINANCE']);
        const lead = findLead(draft, payload.leadId);
        const offer = required(latestForLead(draft.offers, lead.id), 'OFFER_NOT_FOUND', 'Không tìm thấy offer.');
        if (offer.status !== 'ACCEPTED') throw new CommandError('OFFER_NOT_ACCEPTED', 'Offer chưa được chấp nhận.');
        const invoice = { id: uid('invoice'), leadId: lead.id, learnerId: lead.learnerId, offerId: offer.id, amount: offer.total, currency: offer.currency, status: 'ISSUED', mode: 'MOCK', issuedAt: nowIso(), dueAt: new Date(new Date(nowIso()).getTime() + 3 * 86400000).toISOString() };
        draft.invoices.push(invoice);
        appendEvent(draft, context, 'INVOICE_ISSUED', 'INVOICE', invoice.id, `Hóa đơn mock ${invoice.amount.toLocaleString('vi-VN')} ${invoice.currency}.`, { learnerId: lead.learnerId });
        appendAudit(draft, context, 'MOCK_INVOICE_ISSUED', 'INVOICE', invoice.id, 'Hóa đơn demo, không phải chứng từ tài chính thật.');
        return { message: 'Đã phát hành hóa đơn mock.' };
      },

      RECORD_MOCK_PAYMENT(draft, payload, context) {
        requireRole(context.actor, ['FINANCE']);
        const lead = findLead(draft, payload.leadId);
        const invoice = required(latestForLead(draft.invoices, lead.id), 'INVOICE_NOT_FOUND', 'Không tìm thấy hóa đơn.');
        if (invoice.status !== 'ISSUED') throw new CommandError('INVOICE_NOT_PAYABLE', 'Hóa đơn không ở trạng thái chờ thanh toán.');
        invoice.status = 'PAID';
        invoice.paidAt = nowIso();
        const payment = { id: uid('payment'), invoiceId: invoice.id, leadId: lead.id, learnerId: lead.learnerId, amount: invoice.amount, currency: invoice.currency, reference: payload.reference || uid('MOCK'), provider: 'DEMO_LEDGER', mode: 'MOCK', status: 'PAID', paidAt: nowIso() };
        draft.payments.push(payment);
        lead.status = 'WON';
        appendEvent(draft, context, 'PAYMENT_RECORDED', 'PAYMENT', payment.id, `Đã ghi nhận thanh toán mock cho ${lead.name}.`, { learnerId: lead.learnerId });
        appendAudit(draft, context, 'MOCK_PAYMENT_RECORDED', 'PAYMENT', payment.id, `${payment.reference} · DEMO_LEDGER.`);
        notifyRole(draft, 'STUDENT_SERVICE', 'Học viên đã đủ điều kiện xếp lớp', `${lead.name} đã hoàn tất payment mock.`, '/app/service/allocation');
        return { message: 'Đã ghi nhận thanh toán mock.' };
      },

      ALLOCATE_CLASS(draft, payload, context) {
        requireRole(context.actor, ['STUDENT_SERVICE']);
        const lead = findLead(draft, payload.leadId);
        const classItem = required(draft.classes.find((item) => item.id === payload.classId), 'CLASS_NOT_FOUND', 'Không tìm thấy lớp.');
        const activeCount = draft.enrollments.filter((item) => item.classId === classItem.id && item.status === 'ACTIVE').length;
        if (activeCount >= classItem.capacity || classItem.status === 'FULL') {
          const alternatives = draft.classes
            .filter((item) => item.id !== classItem.id && item.courseVersionId === classItem.courseVersionId && ['OPEN', 'ACTIVE'].includes(item.status))
            .map((item) => ({ classId: item.id, name: item.name, seats: item.capacity - draft.enrollments.filter((enrollment) => enrollment.classId === item.id && enrollment.status === 'ACTIVE').length, scheduleLabel: item.scheduleLabel }))
            .filter((item) => item.seats > 0)
            .sort((a, b) => b.seats - a.seats);
          throw new CommandError('NO_SEAT', 'Lớp đã hết chỗ; cần chọn phương án thay thế.', { alternatives });
        }
        const learner = required(draft.learners.find((item) => item.id === lead.learnerId), 'LEARNER_NOT_FOUND', 'Lead chưa có learner profile.');
        const paid = draft.payments.some((item) => item.leadId === lead.id && item.status === 'PAID');
        if (!paid) throw new CommandError('PAYMENT_REQUIRED', 'Cần ghi nhận thanh toán trước khi xếp lớp.');
        if (draft.enrollments.some((item) => item.learnerId === learner.id && item.status === 'ACTIVE')) throw new CommandError('ACTIVE_ENROLLMENT_EXISTS', 'Học viên đã có enrollment đang hoạt động.');
        const enrollment = { id: uid('enrollment'), learnerId: learner.id, classId: classItem.id, courseVersionId: classItem.courseVersionId, status: 'ACTIVE', startsAt: nowIso(), endsAt: null, allocatedBy: context.actor.id };
        draft.enrollments.push(enrollment);
        learner.classId = classItem.id;
        learner.branchId = classItem.branchId;
        learner.status = 'ACTIVE';
        appendEvent(draft, context, 'LEARNER_ALLOCATED', 'ENROLLMENT', enrollment.id, `${learner.name} vào lớp ${classItem.name}.`, { learnerId: learner.id });
        appendAudit(draft, context, 'CLASS_ALLOCATED', 'ENROLLMENT', enrollment.id, `Payment cleared · ${classItem.code}.`);
        notifyRole(draft, 'ACADEMIC_MANAGER', 'Lớp cần gán giáo viên', `${classItem.name} có learner mới.`, '/app/academic/assignments');
        return { message: 'Đã xếp lớp và tạo enrollment.' };
      },

      TRANSFER_ENROLLMENT(draft, payload, context) {
        requireRole(context.actor, ['STUDENT_SERVICE']);
        if (!String(payload.reason || '').trim()) throw new CommandError('REASON_REQUIRED', 'Chuyển lớp cần có lý do.');
        const current = required(draft.enrollments.find((item) => item.learnerId === payload.learnerId && item.status === 'ACTIVE'), 'ACTIVE_ENROLLMENT_NOT_FOUND', 'Không tìm thấy enrollment đang hoạt động.');
        const nextClass = required(draft.classes.find((item) => item.id === payload.toClassId), 'CLASS_NOT_FOUND', 'Không tìm thấy lớp đích.');
        const occupied = draft.enrollments.filter((item) => item.classId === nextClass.id && item.status === 'ACTIVE').length;
        if (occupied >= nextClass.capacity) throw new CommandError('NO_SEAT', 'Lớp đích đã hết chỗ.', { alternatives: [] });
        current.status = 'TRANSFERRED';
        current.endsAt = nowIso();
        current.transferReason = payload.reason.trim();
        const replacement = { id: uid('enrollment'), learnerId: payload.learnerId, classId: nextClass.id, courseVersionId: nextClass.courseVersionId, status: 'ACTIVE', startsAt: nowIso(), endsAt: null, transferredFromId: current.id, allocatedBy: context.actor.id };
        draft.enrollments.push(replacement);
        const learner = draft.learners.find((item) => item.id === payload.learnerId);
        learner.classId = nextClass.id;
        learner.branchId = nextClass.branchId;
        appendEvent(draft, context, 'ENROLLMENT_TRANSFERRED', 'ENROLLMENT', replacement.id, `${learner.name} chuyển sang ${nextClass.name}.`, { learnerId: learner.id });
        appendAudit(draft, context, 'ENROLLMENT_TRANSFERRED', 'ENROLLMENT', replacement.id, payload.reason.trim());
        return { message: 'Đã chuyển lớp và giữ nguyên lịch sử enrollment cũ.' };
      },

      CREATE_RENEWAL(draft, payload, context) {
        requireRole(context.actor, ['ADMISSIONS']);
        const learner = required(draft.learners.find((item) => item.id === payload.learnerId), 'LEARNER_NOT_FOUND', 'Không tìm thấy học viên.');
        const promotion = draft.promotionDecisions.find((item) => item.learnerId === learner.id && item.decision === 'PROMOTE' && item.status === 'FINAL');
        if (!promotion) throw new CommandError('PROMOTION_REQUIRED', 'Cần quyết định promotion đã chốt trước khi tạo renewal.');
        const packageItem = required(draft.packages.find((item) => item.id === payload.packageId), 'PACKAGE_NOT_FOUND', 'Không tìm thấy package.');
        const renewal = { id: uid('renewal'), learnerId: learner.id, nextCourseVersionId: promotion.nextCourseVersionId, packageId: packageItem.id, status: 'OFFERED', outcome: promotion.decision, nextGoal: 'Tiếp tục A2.2 và tăng speaking confidence', offeredAt: nowIso(), ownerId: context.actor.id };
        draft.renewals.push(renewal);
        appendEvent(draft, context, 'RENEWAL_OFFERED', 'RENEWAL', renewal.id, `Đã tạo renewal cho ${learner.name}.`, { learnerId: learner.id });
        appendAudit(draft, context, 'RENEWAL_OFFERED', 'RENEWAL', renewal.id, `Next course: ${promotion.nextCourseVersionId}.`);
        return { message: 'Đã tạo renewal offer.' };
      },

      ACCEPT_RENEWAL(draft, payload, context) {
        requireRole(context.actor, ['ADMISSIONS']);
        const renewal = required(draft.renewals.find((item) => item.learnerId === payload.learnerId && item.status === 'OFFERED'), 'RENEWAL_NOT_FOUND', 'Không tìm thấy renewal đang chờ.');
        renewal.status = 'ACCEPTED';
        renewal.acceptedAt = nowIso();
        appendEvent(draft, context, 'RENEWAL_ACCEPTED', 'RENEWAL', renewal.id, 'Phụ huynh đã chấp nhận lộ trình tiếp theo.', { learnerId: renewal.learnerId });
        appendAudit(draft, context, 'RENEWAL_ACCEPTED', 'RENEWAL', renewal.id, 'Admissions ghi nhận xác nhận trong demo.');
        return { message: 'Đã hoàn tất renewal.' };
      },

      PUBLISH_COURSE_VERSION(draft, payload, context) {
        requireRole(context.actor, ['ACADEMIC_MANAGER']);
        const version = required(draft.courseVersions.find((item) => item.id === payload.courseVersionId), 'COURSE_VERSION_NOT_FOUND', 'Không tìm thấy course version.');
        if (version.status === 'PUBLISHED' && version.immutable) throw new CommandError('COURSE_VERSION_IMMUTABLE', 'Course version đã publish là immutable.');
        if (!['DRAFT', 'APPROVED'].includes(version.status)) throw new CommandError('INVALID_COURSE_VERSION_STATE', 'Course version chưa sẵn sàng để publish.');
        version.status = 'PUBLISHED';
        version.immutable = true;
        version.publishedAt = nowIso();
        appendEvent(draft, context, 'COURSE_VERSION_PUBLISHED', 'COURSE_VERSION', version.id, `${version.title} đã publish.`);
        appendAudit(draft, context, 'COURSE_VERSION_PUBLISHED', 'COURSE_VERSION', version.id, 'Khóa snapshot curriculum.');
        return { message: 'Đã publish course version.' };
      },

      PROPOSE_TEACHER_ASSIGNMENT(draft, payload, context) {
        requireRole(context.actor, ['ACADEMIC_MANAGER']);
        const profile = required(draft.teacherProfiles.find((item) => item.userId === payload.teacherId), 'TEACHER_NOT_FOUND', 'Không tìm thấy teacher profile.');
        const cohort = required(draft.classes.find((item) => item.id === payload.classId), 'CLASS_NOT_FOUND', 'Không tìm thấy lớp.');
        const evidence = root.YC.selectors.teacherEligibility(draft, payload.teacherId, cohort.id, Number(payload.workloadMinutes || 720));
        if (!evidence.eligible) throw new CommandError('TEACHER_INELIGIBLE', 'Giáo viên không vượt qua eligibility gate.', { evidence });
        if (draft.teacherAssignments.some((item) => item.classId === cohort.id && ['PROPOSED', 'ACCEPTED', 'ACTIVE'].includes(item.status))) {
          throw new CommandError('CLASS_ALREADY_ASSIGNED', 'Lớp đã có teacher assignment đang hiệu lực.');
        }
        const assignment = {
          id: uid('teacher-assignment'),
          teacherProfileId: profile.id,
          classId: cohort.id,
          role: 'PRIMARY',
          startsAt: nowIso(),
          endsAt: new Date(new Date(nowIso()).getTime() + 120 * 86400000).toISOString(),
          workloadMinutes: Number(payload.workloadMinutes || 720),
          status: 'PROPOSED',
          proposedAt: nowIso(),
          assignedBy: context.actor.id,
          eligibilityEvidence: evidence,
        };
        draft.teacherAssignments.push(assignment);
        appendEvent(draft, context, 'TEACHER_ASSIGNMENT_PROPOSED', 'TEACHER_ASSIGNMENT', assignment.id, `${draft.users.find((item) => item.id === payload.teacherId)?.name} được đề xuất cho ${cohort.name}.`);
        appendAudit(draft, context, 'TEACHER_ASSIGNMENT_PROPOSED', 'TEACHER_ASSIGNMENT', assignment.id, 'Eligibility hard gates đều đạt.');
        draft.notifications.unshift({ id: uid('notification'), userId: payload.teacherId, title: 'Có đề xuất nhận lớp mới', body: cohort.name, link: '/app/teacher/dashboard', read: false, createdAt: nowIso() });
        return { message: 'Đã gửi đề xuất assignment cho giáo viên.', evidence };
      },

      ACCEPT_TEACHER_ASSIGNMENT(draft, payload, context) {
        requireRole(context.actor, ['TEACHER']);
        const profile = required(draft.teacherProfiles.find((item) => item.userId === context.actor.id), 'TEACHER_NOT_FOUND', 'Không tìm thấy teacher profile.');
        const assignment = required(draft.teacherAssignments.find((item) => item.teacherProfileId === profile.id && item.classId === payload.classId && item.status === 'PROPOSED'), 'ASSIGNMENT_NOT_FOUND', 'Không tìm thấy đề xuất assignment.');
        assignment.status = 'ACTIVE';
        assignment.acceptedAt = nowIso();
        draft.sessionAssignments.push(...draft.sessions.filter((item) => item.classId === assignment.classId).map((session) => ({ id: uid('session-assignment'), sessionId: session.id, teacherProfileId: profile.id, role: assignment.role, status: 'ACTIVE', startsAt: assignment.startsAt, endsAt: assignment.endsAt })));
        appendEvent(draft, context, 'TEACHER_ASSIGNMENT_ACCEPTED', 'TEACHER_ASSIGNMENT', assignment.id, 'Giáo viên đã nhận lớp.');
        appendAudit(draft, context, 'TEACHER_ASSIGNMENT_ACTIVATED', 'TEACHER_ASSIGNMENT', assignment.id, 'Quyền lớp có hiệu lực theo thời hạn assignment.');
        notifyRole(draft, 'ACADEMIC_MANAGER', 'Giáo viên đã nhận lớp', `${context.actor.name} đã nhận assignment.`, '/app/academic/assignments');
        return { message: 'Đã nhận lớp và kích hoạt quyền theo assignment.' };
      },

      CONFIRM_SESSION(draft, payload, context) {
        requireRole(context.actor, ['ACADEMIC_MANAGER', 'STUDENT_SERVICE']);
        const session = required(draft.sessions.find((item) => item.id === payload.sessionId), 'SESSION_NOT_FOUND', 'Không tìm thấy buổi học.');
        if (session.status !== 'PLANNED') throw new CommandError('INVALID_SESSION_STATE', 'Chỉ buổi Planned mới được confirm.');
        const cohort = draft.classes.find((item) => item.id === session.classId);
        const conflicts = root.YC.selectors.scheduleConflicts(draft, { teacherId: payload.teacherId, branchId: cohort.branchId, room: session.room, startsAt: session.startsAt, endsAt: session.endsAt });
        if (conflicts.length) throw new CommandError('SCHEDULE_CONFLICT', 'Lịch bị trùng giáo viên hoặc phòng.', { evidence: conflicts });
        session.status = 'CONFIRMED';
        appendEvent(draft, context, 'SESSION_CONFIRMED', 'SESSION', session.id, 'Buổi học đã được xác nhận.');
        appendAudit(draft, context, 'SESSION_CONFIRMED', 'SESSION', session.id, 'Đã qua conflict gate.');
        return { message: 'Đã xác nhận buổi học.' };
      },

      MARK_SESSION_READY(draft, payload, context) {
        requireRole(context.actor, ['TEACHER']);
        const session = required(draft.sessions.find((item) => item.id === payload.sessionId), 'SESSION_NOT_FOUND', 'Không tìm thấy buổi học.');
        const profile = draft.teacherProfiles.find((item) => item.userId === context.actor.id);
        const assigned = profile && draft.teacherAssignments.some((item) => item.teacherProfileId === profile.id && item.classId === session.classId && item.status === 'ACTIVE');
        if (!assigned) throw new CommandError('SESSION_NOT_ASSIGNED', 'Giáo viên không được assign vào lớp này.');
        const plan = required(draft.lessonPlans.find((item) => item.sessionId === session.id), 'LESSON_PLAN_NOT_FOUND', 'Buổi học chưa có lesson plan.');
        plan.adaptations = payload.adaptations || plan.adaptations;
        plan.readiness = 'READY';
        plan.readyAt = nowIso();
        appendEvent(draft, context, 'SESSION_READY', 'LESSON_PLAN', plan.id, 'Giáo viên xác nhận sẵn sàng trước buổi học.');
        appendAudit(draft, context, 'SESSION_READY', 'LESSON_PLAN', plan.id, `${plan.adaptations.length} adaptation.`);
        return { message: 'Đã xác nhận lesson plan sẵn sàng.' };
      },

      START_SESSION(draft, payload, context) {
        requireRole(context.actor, ['TEACHER']);
        const session = required(draft.sessions.find((item) => item.id === payload.sessionId), 'SESSION_NOT_FOUND', 'Không tìm thấy buổi học.');
        const plan = draft.lessonPlans.find((item) => item.sessionId === session.id);
        if (!plan || plan.readiness !== 'READY') throw new CommandError('SESSION_NOT_READY', 'Cần xác nhận lesson plan sẵn sàng trước khi bắt đầu.');
        if (session.status !== 'CONFIRMED') throw new CommandError('INVALID_SESSION_STATE', 'Chỉ buổi Confirmed mới được bắt đầu.');
        session.status = 'IN_PROGRESS';
        session.actualStartsAt = nowIso();
        appendEvent(draft, context, 'SESSION_STARTED', 'SESSION', session.id, 'Giáo viên check-in và bắt đầu buổi học.');
        appendAudit(draft, context, 'TEACHER_CHECKED_IN', 'SESSION', session.id, context.actor.name);
        return { message: 'Buổi học đã bắt đầu.' };
      },

      COMPLETE_SESSION(draft, payload, context) {
        requireRole(context.actor, ['TEACHER']);
        const session = required(draft.sessions.find((item) => item.id === payload.sessionId), 'SESSION_NOT_FOUND', 'Không tìm thấy buổi học.');
        if (session.status !== 'IN_PROGRESS') throw new CommandError('INVALID_SESSION_STATE', 'Buổi học phải đang diễn ra trước khi hoàn tất.');
        const taughtItemIds = payload.taughtItemIds || [];
        if (!taughtItemIds.length) throw new CommandError('DELIVERY_EVIDENCE_REQUIRED', 'Cần ghi nhận ít nhất một learning item đã dạy.');
        const delivery = {
          id: uid('delivery'),
          sessionId: session.id,
          teacherId: context.actor.id,
          actualStartsAt: session.actualStartsAt,
          actualEndsAt: nowIso(),
          taughtItemIds,
          deferredItemIds: payload.deferredItemIds || [],
          note: payload.note || '',
          coverageStatus: (payload.deferredItemIds || []).length ? 'GAP' : 'COMPLETE',
          status: 'RECORDED',
        };
        draft.deliveryRecords.push(delivery);
        session.status = 'COMPLETED';
        session.actualEndsAt = delivery.actualEndsAt;
        appendEvent(draft, context, 'DELIVERY_RECORDED', 'DELIVERY_RECORD', delivery.id, `${taughtItemIds.length} item đã dạy, ${delivery.deferredItemIds.length} item deferred.`);
        appendAudit(draft, context, 'SESSION_COMPLETED', 'SESSION', session.id, payload.note || 'Delivery evidence complete.');
        if (delivery.coverageStatus === 'GAP') notifyRole(draft, 'ACADEMIC_MANAGER', 'Có coverage gap cần theo dõi', payload.note || 'Buổi học có nội dung deferred.', '/app/academic/dashboard');
        return { message: 'Đã hoàn tất session và lưu delivery evidence.' };
      },

      CORRECT_ATTENDANCE(draft, payload, context) {
        requireRole(context.actor, ['STUDENT_SERVICE', 'ACADEMIC_MANAGER']);
        if (!String(payload.reason || '').trim()) throw new CommandError('REASON_REQUIRED', 'Sửa attendance cần lý do để audit.');
        const record = required(draft.attendanceRecords.find((item) => item.id === payload.attendanceId), 'ATTENDANCE_NOT_FOUND', 'Không tìm thấy attendance record.');
        const previous = record.status;
        record.status = payload.status;
        record.correctedAt = nowIso();
        record.correctedBy = context.actor.id;
        record.correctionReason = payload.reason.trim();
        appendEvent(draft, context, 'ATTENDANCE_CORRECTED', 'ATTENDANCE', record.id, `${previous} → ${record.status}.`, { learnerId: record.learnerId });
        appendAudit(draft, context, 'ATTENDANCE_CORRECTED', 'ATTENDANCE', record.id, payload.reason.trim());
        return { message: 'Đã sửa attendance với đầy đủ lý do.' };
      },

      REQUEST_SUBSTITUTION(draft, payload, context) {
        requireRole(context.actor, ['STUDENT_SERVICE', 'ACADEMIC_MANAGER']);
        if (!String(payload.reason || '').trim()) throw new CommandError('REASON_REQUIRED', 'Yêu cầu dạy thay cần lý do.');
        const session = required(draft.sessions.find((item) => item.id === payload.sessionId), 'SESSION_NOT_FOUND', 'Không tìm thấy buổi học.');
        if (draft.substitutions.some((item) => item.sessionId === session.id && !['CLOSED', 'CANCELLED'].includes(item.status))) throw new CommandError('SUBSTITUTION_EXISTS', 'Buổi học đã có substitution đang xử lý.');
        const primary = draft.teacherAssignments.find((item) => item.classId === session.classId && item.status === 'ACTIVE');
        const substitution = { id: uid('substitution'), sessionId: session.id, originalTeacherProfileId: primary?.teacherProfileId || null, replacementTeacherProfileId: null, reason: payload.reason.trim(), status: 'REQUESTED', handover: null, requestedBy: context.actor.id, requestedAt: nowIso(), accessStartsAt: null, accessEndsAt: null };
        draft.substitutions.push(substitution);
        appendEvent(draft, context, 'SUBSTITUTION_REQUESTED', 'SUBSTITUTION', substitution.id, payload.reason.trim());
        appendAudit(draft, context, 'SUBSTITUTION_REQUESTED', 'SUBSTITUTION', substitution.id, payload.reason.trim());
        return { message: 'Đã mở yêu cầu tìm giáo viên dạy thay.' };
      },

      CONFIRM_SUBSTITUTE(draft, payload, context) {
        requireRole(context.actor, ['STUDENT_SERVICE', 'ACADEMIC_MANAGER']);
        const substitution = required(draft.substitutions.find((item) => item.sessionId === payload.sessionId && item.status === 'REQUESTED'), 'SUBSTITUTION_NOT_FOUND', 'Không tìm thấy yêu cầu substitution.');
        const session = draft.sessions.find((item) => item.id === payload.sessionId);
        const eligibility = root.YC.selectors.teacherEligibility(draft, payload.replacementTeacherId, session.classId, 90);
        if (!eligibility.eligible) throw new CommandError('TEACHER_INELIGIBLE', 'Giáo viên dạy thay không vượt qua eligibility gate.', { evidence: eligibility });
        const replacement = draft.teacherProfiles.find((item) => item.userId === payload.replacementTeacherId);
        substitution.replacementTeacherProfileId = replacement.id;
        substitution.status = 'CONFIRMED';
        substitution.confirmedAt = nowIso();
        substitution.accessStartsAt = new Date(new Date(session.startsAt).getTime() - 86400000).toISOString();
        substitution.accessEndsAt = new Date(new Date(session.endsAt).getTime() + 86400000).toISOString();
        appendEvent(draft, context, 'SUBSTITUTE_CONFIRMED', 'SUBSTITUTION', substitution.id, `${draft.users.find((item) => item.id === payload.replacementTeacherId)?.name} đã được chọn.`);
        appendAudit(draft, context, 'SUBSTITUTE_ACCESS_GRANTED', 'SUBSTITUTION', substitution.id, 'Quyền theo session trong handover window.');
        return { message: 'Đã xác nhận giáo viên dạy thay.' };
      },

      MARK_HANDOVER_READY(draft, payload, context) {
        requireRole(context.actor, ['TEACHER', 'STUDENT_SERVICE']);
        const substitution = required(draft.substitutions.find((item) => item.sessionId === payload.sessionId && item.status === 'CONFIRMED'), 'SUBSTITUTION_NOT_CONFIRMED', 'Substitution chưa được xác nhận.');
        if (!String(payload.note || '').trim()) throw new CommandError('HANDOVER_REQUIRED', 'Cần nội dung handover.');
        substitution.handover = { note: payload.note.trim(), lessonTemplateId: draft.sessions.find((item) => item.id === payload.sessionId)?.lessonTemplateId, openHomeworkIds: draft.homeworkAssignments.filter((item) => item.classId === draft.sessions.find((session) => session.id === payload.sessionId)?.classId).map((item) => item.id), preparedBy: context.actor.id, preparedAt: nowIso() };
        substitution.status = 'HANDOVER_READY';
        appendEvent(draft, context, 'SUBSTITUTION_HANDOVER_READY', 'SUBSTITUTION', substitution.id, payload.note.trim());
        appendAudit(draft, context, 'SUBSTITUTION_HANDOVER_READY', 'SUBSTITUTION', substitution.id, 'Lesson, risk và homework context đã sẵn sàng.');
        return { message: 'Handover package đã sẵn sàng.' };
      },

      CLOSE_SUBSTITUTION(draft, payload, context) {
        requireRole(context.actor, ['STUDENT_SERVICE', 'ACADEMIC_MANAGER']);
        const substitution = required(draft.substitutions.find((item) => item.sessionId === payload.sessionId && !['CLOSED', 'CANCELLED'].includes(item.status)), 'SUBSTITUTION_NOT_FOUND', 'Không tìm thấy substitution.');
        if (substitution.status !== 'HANDOVER_READY') throw new CommandError('HANDOVER_NOT_READY', 'Cần hoàn tất handover trước khi đóng substitution.');
        substitution.status = 'CLOSED';
        substitution.closedAt = nowIso();
        appendEvent(draft, context, 'SUBSTITUTION_CLOSED', 'SUBSTITUTION', substitution.id, 'Đã đóng substitution và giới hạn access window.');
        appendAudit(draft, context, 'SUBSTITUTION_CLOSED', 'SUBSTITUTION', substitution.id, 'Handover evidence retained.');
        return { message: 'Đã đóng substitution.' };
      },

      BOOK_MAKE_UP(draft, payload, context) {
        requireRole(context.actor, ['STUDENT_SERVICE']);
        const attendance = required(draft.attendanceRecords.find((item) => item.id === payload.attendanceId && ['ABSENT', 'EXCUSED'].includes(item.status)), 'MAKE_UP_NOT_ELIGIBLE', 'Attendance chưa đủ điều kiện học bù.');
        const session = required(draft.sessions.find((item) => item.id === payload.makeUpSessionId), 'SESSION_NOT_FOUND', 'Không tìm thấy buổi học bù.');
        const booking = { id: uid('make-up'), learnerId: attendance.learnerId, sourceAttendanceId: attendance.id, sessionId: session.id, status: 'BOOKED', bookedBy: context.actor.id, bookedAt: nowIso() };
        draft.makeUpBookings.push(booking);
        appendEvent(draft, context, 'MAKE_UP_BOOKED', 'MAKE_UP', booking.id, 'Đã đặt buổi học bù.', { learnerId: booking.learnerId });
        appendAudit(draft, context, 'MAKE_UP_BOOKED', 'MAKE_UP', booking.id, `Session ${session.id}.`);
        return { message: 'Đã đặt buổi học bù.' };
      },
    };

    function dispatch(name, payload = {}, actorId) {
      const handler = handlers[name];
      if (!handler) return { ok: false, code: 'UNKNOWN_COMMAND', message: `Command không tồn tại: ${name}` };
      const eventIds = [];
      try {
        let output;
        store.transact((draft) => {
          const actor = required(draft.users.find((item) => item.id === actorId), 'ACTOR_NOT_FOUND', 'Không tìm thấy người thực hiện.');
          const context = { actor, eventIds };
          output = handler(draft, payload, context) || {};
        });
        return { ok: true, eventIds, message: output.message || 'Đã cập nhật.', ...output };
      } catch (error) {
        if (error instanceof CommandError) {
          return { ok: false, code: error.code, message: error.message, alternatives: error.alternatives || [], evidence: error.evidence || null };
        }
        throw error;
      }
    }

    return Object.freeze({ dispatch, registered: Object.freeze(Object.keys(handlers)) });
  }

  root.YC.define('commands', Object.freeze({ CommandError, create }));
})(globalThis);

/* 06-selectors.js */
(function defineSelectors(root) {
  'use strict';

  const ROLE_HOME = Object.freeze({
    ADMIN: '/app/admin/dashboard',
    CENTER_MANAGER: '/app/manager/dashboard',
    ADMISSIONS: '/app/admissions/dashboard',
    ACADEMIC_MANAGER: '/app/academic/dashboard',
    STUDENT_SERVICE: '/app/service/dashboard',
    FINANCE: '/app/finance/dashboard',
    TEACHER: '/app/teacher/dashboard',
    TA: '/app/teacher/dashboard',
    STUDENT: '/app/student/dashboard',
    PARENT: '/app/parent/dashboard',
  });

  function byId(state, collection, id) {
    return (state[collection] || []).find((item) => item.id === id) || null;
  }

  function roleHome(role) {
    return ROLE_HOME[role] || '/login';
  }

  function journey(state) {
    const learnerId = state.demo.canonicalLearnerId;
    const lead = state.leads.find((item) => item.learnerId === learnerId);
    const checks = [
      { status: 'LEAD', ownerRole: 'ADMISSIONS', done: lead && lead.status !== 'NEW' },
      { status: 'PLACEMENT', ownerRole: 'ADMISSIONS', done: state.placementResults.some((item) => item.learnerId === learnerId && item.status === 'RELEASED') },
      { status: 'PAID', ownerRole: 'FINANCE', done: state.payments.some((item) => item.learnerId === learnerId && item.status === 'PAID') },
      { status: 'ENROLLED', ownerRole: 'STUDENT_SERVICE', done: state.enrollments.some((item) => item.learnerId === learnerId && item.status === 'ACTIVE') },
      { status: 'TEACHER_ASSIGNED', ownerRole: 'ACADEMIC_MANAGER', done: state.teacherAssignments.some((item) => item.classId === 'class-6a' && item.status === 'ACTIVE') },
      { status: 'SESSION_DELIVERED', ownerRole: 'TEACHER', done: state.deliveryRecords.some((item) => item.sessionId === 'session-canonical') },
      { status: 'REMEDIAL_ASSIGNED', ownerRole: 'TEACHER', done: state.remedialAssignments.some((item) => item.learnerId === learnerId) },
      { status: 'REMEDIAL_COMPLETED', ownerRole: 'STUDENT', done: state.remedialAssignments.some((item) => item.learnerId === learnerId && item.status === 'COMPLETED') },
      { status: 'MODERATED', ownerRole: 'ACADEMIC_MANAGER', done: state.moderationCases.some((item) => item.learnerId === learnerId && item.status === 'APPROVED') },
      { status: 'PROGRESS_PUBLISHED', ownerRole: 'ACADEMIC_MANAGER', done: state.progressReports.some((item) => item.learnerId === learnerId && item.status === 'PUBLISHED') },
      { status: 'PARENT_REVIEWED', ownerRole: 'PARENT', done: state.domainEvents.some((item) => item.type === 'PARENT_PROGRESS_VIEWED' && item.learnerId === learnerId) },
      { status: 'RENEWED', ownerRole: 'ADMISSIONS', done: state.renewals.some((item) => item.learnerId === learnerId && item.status === 'ACCEPTED') },
    ];
    const index = checks.findIndex((item) => !item.done);
    if (index === -1) return { status: 'RENEWED', index: 11, total: checks.length, ownerRole: 'ADMISSIONS' };
    return { status: checks[index].status, index, total: checks.length, ownerRole: checks[index].ownerRole };
  }

  function metrics(state, role) {
    const activeEnrollments = state.enrollments.filter((item) => item.status === 'ACTIVE');
    const openCases = [...state.serviceCases, ...state.interventionCases].filter((item) => item.status === 'OPEN');
    const common = {
      activeLearners: activeEnrollments.length,
      openCases: openCases.length,
      branchCount: state.branches.filter((item) => item.status === 'ACTIVE').length,
    };
    if (role === 'ADMISSIONS') return { ...common, newLeads: state.leads.filter((item) => item.status === 'NEW').length, renewalDue: state.renewals.filter((item) => item.status === 'DUE').length };
    if (role === 'FINANCE') return { ...common, paidInvoices: state.invoices.filter((item) => item.status === 'PAID').length, mockRevenue: state.payments.filter((item) => item.status === 'PAID').reduce((sum, item) => sum + item.amount, 0) };
    if (role === 'TEACHER') return { ...common, gradingBacklog: state.gradingRecords.filter((item) => !['RELEASED', 'APPROVED'].includes(item.status)).length, upcomingSessions: state.sessions.filter((item) => ['CONFIRMED', 'PLANNED'].includes(item.status)).length };
    return common;
  }

  function teacherWorkload(state, teacherId) {
    const profile = state.teacherProfiles.find((item) => item.userId === teacherId);
    const teachingMinutes = profile
      ? state.teacherAssignments
        .filter((item) => item.teacherProfileId === profile.id && ['ACCEPTED', 'ACTIVE'].includes(item.status))
        .reduce((sum, item) => sum + Number(item.workloadMinutes || 0), 0)
      : 0;
    const preparationMinutes = Math.round(teachingMinutes * 0.2);
    const gradingMinutes = Math.round(teachingMinutes * 0.25);
    const administrationMinutes = Math.round(teachingMinutes * 0.15);
    return {
      teachingMinutes,
      preparationMinutes,
      gradingMinutes,
      administrationMinutes,
      totalMinutes: teachingMinutes + preparationMinutes + gradingMinutes + administrationMinutes,
      limitMinutes: state.settings.workloadLimitMinutes,
    };
  }

  function teacherEligibility(state, teacherId, classId, requestedWorkloadMinutes = 720) {
    const user = state.users.find((item) => item.id === teacherId);
    const profile = state.teacherProfiles.find((item) => item.userId === teacherId);
    const cohort = state.classes.find((item) => item.id === classId);
    const courseVersion = state.courseVersions.find((item) => item.id === cohort?.courseVersionId);
    const levelCode = state.levels.find((item) => item.id === state.courses.find((course) => course.id === courseVersion?.courseId)?.levelId)?.code || '';
    const frameworkLevel = levelCode.split('.')[0];
    const now = new Date(state.seededAt).getTime();
    const qualificationValid = Boolean(profile && state.qualifications.some((item) => item.teacherProfileId === profile.id
      && item.status === 'VALID'
      && new Date(item.expiresAt).getTime() >= now));
    const workload = teacherWorkload(state, teacherId);
    const hardGates = [
      { key: 'ACTIVE_PROFILE', label: 'Hồ sơ đang hoạt động', passed: Boolean(user?.status === 'ACTIVE' && profile?.status === 'ACTIVE') },
      { key: 'QUALIFICATION', label: 'Qualification còn hiệu lực', passed: qualificationValid },
      { key: 'LEVEL', label: `Được phép dạy ${frameworkLevel || 'level yêu cầu'}`, passed: Boolean(profile?.levels.includes(frameworkLevel)) },
      { key: 'AGE_BAND', label: `Có kinh nghiệm ${cohort?.ageBand || 'age band'}`, passed: Boolean(profile?.ageBands.includes(cohort?.ageBand)) },
      { key: 'BRANCH', label: `Được phân scope ${cohort?.branchId || 'chi nhánh'}`, passed: Boolean(profile?.branchIds.includes(cohort?.branchId)) },
      { key: 'MODE', label: `Dạy được mode ${cohort?.mode || ''}`, passed: Boolean(profile?.modes.includes(cohort?.mode) || (cohort?.mode === 'HYBRID' && profile?.modes.includes('ONLINE') && profile?.modes.includes('OFFLINE'))) },
      { key: 'WORKLOAD', label: 'Không vượt giới hạn workload', passed: workload.totalMinutes + Math.round(requestedWorkloadMinutes * 1.6) <= workload.limitMinutes },
    ];
    const rankingSignals = [
      { key: 'BRANCH_CONTINUITY', label: 'Liên tục cùng chi nhánh', score: profile?.branchIds.includes(cohort?.branchId) ? 20 : 0 },
      { key: 'PROGRAM_EXPERIENCE', label: 'Kinh nghiệm cùng level', score: profile?.levels.includes(frameworkLevel) ? 20 : 0 },
      { key: 'LOAD_BALANCE', label: 'Dư địa workload', score: Math.max(0, Math.round((1 - workload.totalMinutes / workload.limitMinutes) * 20)) },
    ];
    return { teacherId, classId, eligible: hardGates.every((item) => item.passed), hardGates, rankingSignals, workload };
  }

  function overlaps(firstStart, firstEnd, secondStart, secondEnd) {
    return new Date(firstStart).getTime() < new Date(secondEnd).getTime()
      && new Date(firstEnd).getTime() > new Date(secondStart).getTime();
  }

  function scheduleConflicts(state, request) {
    const profile = state.teacherProfiles.find((item) => item.userId === request.teacherId);
    const conflicts = [];
    for (const session of state.sessions.filter((item) => !['CANCELLED', 'REVIEWED'].includes(item.status))) {
      if (!overlaps(request.startsAt, request.endsAt, session.startsAt, session.endsAt)) continue;
      if (session.room === request.room && state.classes.find((item) => item.id === session.classId)?.branchId === request.branchId) {
        conflicts.push({ type: 'ROOM', sessionId: session.id, label: `Phòng ${request.room} đã có lịch.` });
      }
      const assigned = profile && state.teacherAssignments.some((item) => item.teacherProfileId === profile.id
        && item.classId === session.classId
        && ['ACCEPTED', 'ACTIVE'].includes(item.status));
      if (assigned) conflicts.push({ type: 'TEACHER', sessionId: session.id, label: 'Giáo viên đã có buổi dạy trùng giờ.' });
    }
    return conflicts;
  }

  function sessionWorkbench(state, sessionId) {
    const session = byId(state, 'sessions', sessionId);
    if (!session) return null;
    const plan = state.lessonPlans.find((item) => item.sessionId === sessionId) || null;
    const learnerIds = state.enrollments.filter((item) => item.classId === session.classId && item.status === 'ACTIVE').map((item) => item.learnerId);
    return {
      session,
      plan,
      roster: state.learners.filter((item) => learnerIds.includes(item.id)),
      risks: state.interventionCases.filter((item) => learnerIds.includes(item.learnerId) && item.status === 'OPEN'),
      openHomework: state.homeworkAssignments.filter((item) => item.classId === session.classId && !['ACCEPTED', 'CLOSED'].includes(item.status)),
      delivery: state.deliveryRecords.find((item) => item.sessionId === sessionId) || null,
    };
  }

  root.YC.define('selectors', Object.freeze({ byId, journey, metrics, roleHome, scheduleConflicts, sessionWorkbench, teacherEligibility, teacherWorkload }));
})(globalThis);
