/* Generated by scripts/build_standalone.py. Do not edit directly. */

/* 00-namespace.js */
(function initializeNamespace(root) {
  'use strict';

  const registry = Object.create(null);
  const YC = root.YC || {};

  YC.define = function define(name, value) {
    if (Object.prototype.hasOwnProperty.call(registry, name)) {
      throw new Error(`Service already defined: ${name}`);
    }
    registry[name] = value;
    YC[name] = value;
    return value;
  };

  YC.require = function requireService(name) {
    if (!Object.prototype.hasOwnProperty.call(registry, name)) {
      throw new Error(`Unknown service: ${name}`);
    }
    return registry[name];
  };

  root.YC = YC;
})(globalThis);

/* 01-utils.js */
(function defineUtilities(root) {
  'use strict';

  let sequence = 0;

  function escapeHtml(value) {
    return String(value ?? '')
      .replaceAll('&', '&amp;')
      .replaceAll('<', '&lt;')
      .replaceAll('>', '&gt;')
      .replaceAll('"', '&quot;')
      .replaceAll("'", '&#039;');
  }

  function uid(prefix = 'id') {
    sequence += 1;
    return `${prefix}-${Date.now().toString(36)}-${sequence.toString(36)}`;
  }

  function clone(value) {
    if (typeof structuredClone === 'function') return structuredClone(value);
    return JSON.parse(JSON.stringify(value));
  }

  function dateAt(clock, dayOffset = 0, hour = 9, minute = 0) {
    const date = new Date(clock());
    date.setHours(hour, minute, 0, 0);
    date.setDate(date.getDate() + dayOffset);
    return date.toISOString();
  }

  function formatDate(value, includeTime = false) {
    const options = includeTime
      ? { dateStyle: 'short', timeStyle: 'short' }
      : { day: '2-digit', month: '2-digit', year: 'numeric' };
    return new Intl.DateTimeFormat('vi-VN', options).format(new Date(value));
  }

  function percent(part, total) {
    return total ? Math.round((part / total) * 100) : 0;
  }

  root.YC.define('utils', Object.freeze({
    clone,
    dateAt,
    escapeHtml,
    formatDate,
    percent,
    uid,
  }));
})(globalThis);
